### PR TITLE
1st milestone - all screen sizes web clone

### PR DESCRIPTION
**Pull request by vitorelourenco**
The assets of the page were acquired
The HTML structure of the page was laid out
The elements were styled and positioned in order to mimic the original website
Media queries were included to make the website responsive
Elements that were supposed to be either displayed or hidden depending on the screen size were properly styled.
Linter errors were checked.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello team,
Great work on the project. This is a really professional looking project. The responsiveness is off the chart. Amazing👌👌.
However let's make some small changes.

[REQUIRED]: Work on all the sections of the page. You skipped the middle sections
[OPTIONAL]: Put the CSS files in one files and use the media queries in CSS file, not in the HTML page.

giphy (2)

Make the requested changes and ask for another review👌
Happy coding💻💻

**Comment by vitorelourenco** [comment]
> ### **STATUS: CHANGES REQUESTED🛑🛑🛑**
> Hello team,
> Great work on the project. This is a really professional looking project. The responsiveness is off the chart. Amazing👌👌.
> However let's make some small changes.
> 
> [REQUIRED]: Work on all the sections of the page. You skipped the middle sections
> [OPTIONAL]: Put the CSS files in one files and use the media queries in CSS file, not in the HTML page.
> 
> giphy (2)
> 
> Make the requested changes and ask for another review👌
> Happy coding💻💻

We've worked on all the sections of the page required for the first milestone which is what was asked of us for today's deadline

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

Hey @Maha-Magdy & @vitorelourenco, 👋🏽 

### Thank you for the TNW clone, looks almost the same. I like the fact that you have used sematic HTML with this project.

🟥  However, there are a few issues to fix to get going. 

## REQUIRED CHANGES 🟨 

- [x] The logo should be embedded inside an `<a>` tag.
- [x] The search icon should be embedded inside an `<a>` tag.
- [x] The hamburg icon should be embedded inside an `<a>` tag. **In mobile view**
- [x] The background images should be embedded inside an `<a>` tag.
- [x] The highlights section should be embedded inside `<article>` tags for each article.
- [x] The social media links in the footer should be in a `nav` tag.


### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

**Comment by vitorelourenco** [comment]
> # **STATUS: CHANGES REQUIRED red_circle warning**
> 
> Hey @Maha-Magdy & @vitorelourenco, 👋🏽
> ### Thank you for the TNW clone, looks almost the same. I like the fact that you have used sematic HTML with this project.
> 
> red_square However, there are a few issues to fix to get going.
> ## REQUIRED CHANGES yellow_square
> 
>     * [x]  The logo should be embedded inside an `<a>` tag.
> 
>     * [x]  The search icon should be embedded inside an `<a>` tag.
> 
>     * [x]  The hamburg icon should be embedded inside an `<a>` tag. **In mobile view**
> 
>     * [x]  The background images should be embedded inside an `<a>` tag.
> 
>     * [x]  The highlights section should be embedded inside `<article>` tags for each article.
> 
>     * [x]  The social media links in the footer should be in a `nav` tag.
> 
> 
> ### Kindly make all the requested changes and submit another CRR. 100
> 
> **Cheers tropical_drink and Happy coding computer**
> ## Reach me on slack for a chit-chat sos Roy Mukuye

Thank you for your feedback. All requested changes have been made.

**Review by rindrajosia — APPROVED** [review]
Status :100: Approved :1st_place_medal:
Great work!! Congrats, the project is approved :heavy_check_mark:

- [ ] [REQUIRED] **Remove all comments in your css files before merging**

Keep up the good work :muscle:
Rindra Josia

**Pull request merged**
